#Sets the URL to send the information to. For help with how to set up a listener, and an example one, go to http://dev.bukkit.org/bukkit-plugins/sendere/.
url: "http://www.minwrit.me/hlysnere.php"
    
#Send players' actions
Chat: true
Join: true
Quit: true
Kick: true
Death: true
    
#Send weather changes
Weather: true