name: Sendere
main: com.jamescl.sendere.Sendere
version: 1.1.0
description: Sendere reports many actions to an HTTP server.
author: James Larsson
commands:
   sendere:
      description: Gives Sendere version, or reloads its configuration.
      usage: /sendere [reload | version]
      permission: sendere.reload
      permission-message: You don't have permission!
permissions:
    sendere.*:
        description: Gives access to all Sendere commands
        children:
            sendere.reload: true
    sendere.reload:
        description: Allows you to reload Sendere's configuration
        default: op